### ISSUE TITLE
What's the usage of AsDomain? Seems like DomainRef suffices

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/DomainSetsCore.jl#2]
https://github.com/JuliaApproximation/DomainSetsCore.jl/blob/4bd09ebec3af8a47122759bc3ddbe1caa277798f/src/DomainSetsCore.jl#L82

**Comment by daanhb** [comment]
I had modelled this after Ref in julia. Ref(5) is also not a concrete type and returns something else:
```julia
julia> Ref(5)
Base.RefValue{Int64}(5)
```
My thinking here was that some objects need not be modified when passed as a domain, for example `AsDomain(d::Domain) = d`. But since `DomainRef` is a concrete type, one would expect it to return an instance of DomainRef.

**Comment by dlfivefifty** [comment]
But a `Domain` is not a subtype of `AsDomain` so `AsDomain(d::Domain) = d` is bad style (type constructors should always return an instance of that type)

**Comment by daanhb** [comment]
That's true. I guess `AsDomain` could just be a function, instead of an abstract type, but then we have more names in total since the user writes `foo(AsDomain(d))` and the developer writes `foo(d::DomainRef) = ...`. We could simply use `DomainRef`, but in that case regular domains would have to be wrapped as well. If that's not too bad, it would admittedly be simpler.

I originally thought that `AsDomain(d)` might also return something else that acts like the domain which `d` is supposed to represent, but thinking about it now that conflates things. There already is a mechanism to convert to a domain.

Only thing left on my mind is why `Ref` is not a concrete type.

**Comment by daanhb** [comment]
I've removed AsDomain and just use DomainRef now. It is simpler.
